# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end
  config.vm.define "server1" do |server1|
    server1.vm.network "public_network", ip: "192.168.3.231", bridge: "en0: Wi-Fi (AirPort)",
      use_dhcp_assigned_default_route: true
  end
  config.vm.define "server2" do |server2|
    server2.vm.network "public_network", ip: "192.168.3.232", bridge: "en0: Wi-Fi (AirPort)",
      use_dhcp_assigned_default_route: true
  end
end
